#......................................................
# Advanced Lesson => __name__and__main__
#......................................................
# if __name__=='__main__' :
#..........................
#  __name__ => Built in variable
#  __main__ => value of the built in variable
#......................................................
# Executing Method :
#..................
# Directly (page script)=> Executing python file using command line
# from import (module script =>page.method())=> import the code from the file to another file(execute in another page)
#......................................................
# in Direct mode python assign value "__main__" 
# to the built in the variable __name__ in back ground
#......................................................
print(__name__)